import {
  tasksValues,
  rankValues,
  p5bValues,
  podrazdValues,
  doljnValues,
} from "./spr";

export const sections = [
  {
    type: "input",
    labelText: "Фамилия",
    labelClass: "form__label",
    placeholder: "Иванов",
    name: "fam",
    set: "brief",
    validate: {
      required: true,
      min: 2,
      max: 60,
      regexp: "/[a-zа-я0-9/s-]+/i",
    },
  },
  {
    type: "input",
    labelText: "Имя",
    labelClass: "form__label",
    placeholder: "Иван",
    name: "imj",
    set: "brief",
    validate: {
      required: true,
      max: 60,
      regexp: "/[a-zа-я0-9/s-]+/i",
    },
  },
  {
    type: "input",
    labelText: "Отчество",
    labelClass: "form__label",
    placeholder: "Иванович",
    name: "otch",
    set: "brief",
    validate: {
      required: true,
      max: 60,
      regexp: "/[a-zа-я0-9/s-]+/i",
    },
  },
  {
    type: "input",
    labelText: "Выбор1",
    labelClass: "form__label",
    placeholder: "введите 'сл вар'",
    name: "input1",
    list: rankValues,
    set: "brief",
    validate: {
      required: false,
      min: 10,
      max: 60,
      regexp: "/[a-zа-я0-9/s-]+/i",
    },
  },
  {
    type: "input",
    labelText: "Выбор2",
    labelClass: "form__label",
    placeholder: "выбор из списка",
    name: "doljn",
    listToInput: "key only",
    set: "brief",
    list: doljnValues,
    validate: {
      required: false,
      min: 3,
      max: 60,
      regexp: "/[-a-zа-я0-9/s/]+/i",
    },
  },
  {
    type: "input",
    labelText: "Выбор3",
    labelClass: "form__label",
    placeholder: "поиск по началу всех введенных слов",
    name: "podrazd",
    list: podrazdValues,
    listToInput: "key only",
    set: "brief",
    validate: {
      required: true,
      min: 2,
      regexp: "/[a-zа-я0-9/s-]+/i",
    },
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    placeholder: "12/234",
    name: "n_kom",
    set: "brief",
    validate: {
      required: true,
      min: 1,
      max: 20,
      regexp: "/[0-9/s-]+/i",
    },
  },
  {
    type: "multichoice",
    labelText: "Мультивыбор",
    labelClass: "form__label",
    placeholder:
      "Ввод нескольких вариантов в свободной форме через Tab или Enter",
    name: "places",
    separators: ["Tab", "Enter"],
    set: "brief",
    validate: {
      required: true,
    },
  },
  {
    type: "switch",
    labelText: "Переключатель 1",
    labelClass: "form__label",
    name: "p4a",
    offValue: ["01", "01 - выбор1"],
    onValue: ["02", "02 - выбор2"],
    set: "brief",
  },
  {
    type: "input",
    labelText: "Тестовое поле",
    labelClass: "form__label",
    placeholder: "Это поле видно если в переключателе1 выбран выбор1",
    name: "p4a_punkt",
    conditions: [["p4a", "01", "="]],
    set: "brief",
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    placeholder: "Текстовое поле",
    name: "p4a_date",
    inputType: "date",
    set: "brief",
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    placeholder: "текстовое поле",
    name: "p4a_n_doc",
    set: "brief",
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    placeholder: "Поле видно если в переключателе1 выбран выбор2",
    name: "p4a_fio",
    conditions: [["p4a", "02", "="]],
    set: "brief",
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    placeholder: "Поле видно если в переключателе1 выбран выбор2",
    list: rankValues,
    name: "p4a_rank",
    conditions: [["p4a", "02", "="]],
    set: "brief",
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    list: podrazdValues,
    placeholder: "Поле видно если в переключателе1 выбран выбор2",
    name: "p4a_doljn",
    conditions: [["p4a", "02", "="]],
    set: "brief",
  },
  {
    type: "switch",
    labelText: "Переключатель 2",
    labelClass: "form__label",
    name: "p5a",
    offValue: ["01", "01 - вариант 1"],
    onValue: ["02", "02 - вариант 2"],
    set: "brief",
  },
  {
    type: "input",
    labelText: "Выбор из списка",
    labelClass: "form__label",
    name: "p5b",
    placeholder: "выберите один из вариантов...",
    list: p5bValues,
    set: "brief",
    defaultValue: "020",
    validate: {
      listOnly: true,
    },
  },
  {
    type: "switch",
    labelText:
      "Переключатель 3",
    labelClass: "form__label",
    name: "p5c",
    offValue: [null, "нет"],
    onValue: ["030", "030 - необязательный вариант"],
  },
  {
    type: "multichoice",
    labelText: "Мультивыбор с выбором из списка, вертикальное расположение выбранных вариантов",
    labelClass: "form__label",
    placeholder: "Ввод кодов через пробел (или начало текста)",
    name: "tasks",
    separators: ["Tab", "Enter", ",", " "],
    list: tasksValues,
    set: "brief",
    multichoiceStyle: "vertical",
  },
  {
    type: "input",
    labelText: "Текстовое поле",
    labelClass: "form__label",
    name: "group_boss",
    conditions: [["p5b", "020", "!="]],
    set: "brief",
  },
  {
    type: "multichoice",
    labelText: "Мультивыбор без справочника, свободный ввод, горизонтальное расположение выбранных вариантов",
    labelClass: "form__label",
    placeholder: "Ввод вариантов через Tab или Enter",
    name: "comission",
    separators: ["Tab", "Enter"],
    conditions: [["p5b", "020", "!="]],
    set: "brief",
  },
];
